function k(b,a,c,d){b.s.jb(b.mb,a,c,d)}function l(b,a,c,d){b.s.ca?k(b,a,c,d):b.s.Ae()._OnMessageFromDOM({type:"event",component:b.mb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.s.C(b.mb,a,c)}function t(b,a){for(const [c,d]of a)n(b,c,d)}function u(b){b.Rb||(b.s.kd(b.Td),b.Rb=!0)}window.eb=class{constructor(b,a){this.s=b;this.mb=a;this.Rb=!1;this.Td=()=>this.Na()}bd(){}Na(){}};
window.lf=class{constructor(){this.Yc=-1}j(){-1!==this.Yc&&(self.clearTimeout(this.Yc),this.Yc=-1)}};"use strict";function aa(b,a){n(b,"get-element",c=>{const d=v(b,c.elementId);return a(d,c)})}function v(b,a){b=b.Pb.get(a);if(!b)throw Error(`no element with id ${a}`);return b.wd}
window.kf=class extends self.eb{constructor(b,a){super(b,a);this.Pb=new Map;this.Fc=!0;t(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=v(this,c);this.Fc&&d.parentElement.removeChild(d);this.Pb.delete(c)}],["set-visible",c=>{if(this.Fc){var d=this.Pb.get(c.elementId),e=d.wd;d.Cd?e.style.display=c.isVisible?"":"none":d.Se=!!c.isVisible}}],["update-position",c=>{if(this.Fc){var d=this.Pb.get(c.elementId),e=d.wd;e.style.left=c.left+"px";e.style.top=c.top+
"px";e.style.width=c.width+"px";e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.Cd||(d.Cd=!0,d.Se&&(e.style.display=""))}}],["update-state",c=>{v(this,c.elementId);throw Error("required override");}],["focus",c=>this.Bc(c)],["set-css-style",c=>{const d=v(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{v(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{v(this,c.elementId).removeAttribute(c.name)}]]);
aa(this,c=>c)}Bc(b){var a=v(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const ba=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),w=/android/i.test(navigator.userAgent),ca=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let da=0;
function y(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.$e?new Promise(c=>{const d="c3_resolve_"+da;++da;self[d]=c;a.textContent=b.df+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ea=!1,fa=!1;function ha(){if(!ea){try{new Worker("blob://",{get type(){fa=!0}})}catch(b){}ea=!0}return fa}let z=new Audio;
const ia={"audio/webm; codecs=opus":!!z.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!z.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!z.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!z.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!z.canPlayType("audio/mp4"),"audio/mpeg":!!z.canPlayType("audio/mpeg")};z=null;async function ja(b){b=await ka(b);return(new TextDecoder("utf-8")).decode(b)}
function ka(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const D=[];let E=0;window.RealFile=window.File;const F=[],G=new Map,H=new Map;let na=0;const oa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");oa.push(b)};const pa=new Set(["cordova","playable-ad","instant-games"]);let qa=!1;
window.Ba=class b{constructor(a){this.ca=a.ff;this.xa=null;this.ba="";this.$a=a.cf;this.Cb={};this.Ta=this.ua=null;this.Ob=[];this.J=this.na=null;this.Nc=!1;this.zd=0;this.rb=null;this.Za=-1;this.We=()=>this.Ie();this.Ya=[];this.Zc=null;this.Ud=[];this.v=a.Vd;this.Sb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ha()||(this.ca=!1);this.ca&&ca&&(this.ca=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.ca=!1;if("cordova"===
this.v&&this.ca)if(w){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.va()?self.chrome.webview.addEventListener("message",c=>this.pd(c.data)):"macos-wkwebview"===this.v&&(self.C3WrapperOnMessage=c=>this.pd(c));this.Vb=this.ra=null;"html5"!==this.v||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");
this.C("runtime","cordova-fetch-local-file",c=>this.Ee(c));this.C("runtime","create-job-worker",()=>this.Fe());this.C("runtime","send-wrapper-extension-message",c=>this.Le(c));"cordova"===this.v?document.addEventListener("deviceready",()=>this.nd(a)):this.nd(a)}j(){this.uc();this.xa&&(this.xa=this.xa.onmessage=null);this.ua&&(this.ua.terminate(),this.ua=null);this.Ta&&(this.Ta.j(),this.Ta=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}pe(){return ba&&"cordova"===this.v}qc(){const a=
navigator.userAgent;return ba&&pa.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}ne(){return w}gd(){return w&&pa.has(this.v)}va(){return"windows-webview2"===this.v||!!("preview"===this.v&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}async nd(a){"macos-wkwebview"===this.v?this.Ea({type:"ready"}):this.va()&&(this.Oe(),this.Ud=(await this.De()).registeredComponentIds);if("playable-ad"===this.v){this.ra=self.c3_base64files;this.Vb={};await this.we();
for(let d=0,e=a.bb.length;d<e;++d){var c=a.bb[d];this.Vb.hasOwnProperty(c)?a.bb[d]={$e:!0,df:this.Vb[c]}:this.ra.hasOwnProperty(c)&&(a.bb[d]=URL.createObjectURL(this.ra[c]))}a.jc=[]}if("nwjs"===this.v&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.kd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.bf?this.ba=a.bf:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.hf&&(this.Cb=a.hf);
c=new MessageChannel;this.xa=c.port1;this.xa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.He(d));this.rb=new self.qe(this);await ra(this.rb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ca?await this.Ce(a,c.port2):
await this.Be(a,c.port2)}wc(a){a=this.Cb.hasOwnProperty(a)?this.Cb[a]:a.endsWith("/workermain.js")&&this.Cb.hasOwnProperty("workermain.js")?this.Cb["workermain.js"]:"playable-ad"===this.v&&this.ra.hasOwnProperty(a)?this.ra[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async lc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.v&&this.Sb)return a=await this.Eb(d.Ze?a:this.$a+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=
new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}pa(){return Math.max(window.innerWidth,1)}ia(){return Math.max(window.innerHeight,1)}md(a){var c=this.ba,d=location.href,e=this.pa(),f=this.ia(),g=window.devicePixelRatio,h=b.hb(),m=a.qf,p=window.cr_previewImageBlobs||this.ra,q=window.cr_previewProjectFileBlobs,A=window.cr_previewProjectFiles,x=window.cr_swClientId||
"";a=a.Vd;var r=(new URLSearchParams(self.location.search)).has("debug"),B=this.rb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:m,previewImageBlobs:p,previewProjectFileBlobs:q,previewProjectFileSWUrls:A,swClientId:x,exportType:a,isDebug:r,ife:!!self.pf,jobScheduler:{inputPort:B.Mc,outputPort:B.Tc,maxNumWorkers:B.Te},supportedAudioFormats:ia,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.$a+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.$a+"opus.wasm.wasm",isFileProtocol:this.Sb,isiOSCordova:this.pe(),isiOSWebView:this.qc(),isWebView2Wrapper:this.va(),wrapperComponentIds:this.Ud,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ce(a,c){const d=this.wc(a.gf);"preview"===this.v?(this.ua=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,m)=>{const p=q=>{this.ua.removeEventListener("message",p);q.data&&"ok"===q.data.type?h():m()};this.ua.addEventListener("message",p);this.ua.postMessage({type:"construct-worker-init",
"import":(new URL(d,this.ba)).toString()})})):this.ua=await this.lc(d,this.ba,{type:"module",name:"Runtime",Ze:!0});this.J=document.createElement("canvas");this.J.style.display="none";const e=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.jc||[],g=a.bb;f=await Promise.all(f.map(h=>this.Oa(h)));g=await Promise.all(g.map(h=>this.Oa(h)));if("cordova"===this.v)for(let h=0,m=a.ic.length;h<
m;++h){const p=a.ic[h],q=p[0];if(q===a.$c||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))p[1]=await this.Oa(q)}this.ua.postMessage(Object.assign(this.md(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.ic,mainProjectScript:a.$c,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...sa(this.rb)]);this.Ob=F.map(h=>new h(this));this.ld();ta(this.na);self.c3_callFunction=(h,m)=>{var p=this.na;return p.s.jd(p.mb,
"js-invoke-function",{name:h,params:m})};"preview"===this.v&&(self.goToLastErrorScript=()=>this.jb("runtime","go-to-last-error-script"))}async Be(a,c){this.J=document.createElement("canvas");this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Ob=F.map(g=>new g(this));this.ld();var d=a.bb.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);if(Array.isArray(a.jc)){var e=[...a.jc].map(g=>
g instanceof Blob?URL.createObjectURL(g):g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.Oa(g)));await Promise.all(d.map(g=>y(g)));d=self.C3_ProjectScriptsStatus;e=a.$c;const f=a.ic;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Oa(h),await y(h),"preview"!==this.v||d[g]||this.qd(g,"main script did not run to completion")}catch(m){this.qd(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Oa(h),await y(h);"preview"===this.v&&"object"!==typeof self.jf.mf?
(this.Jb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.md(a),{isInWorker:!1,messagePort:c,canvas:this.J,runOnStartupFunctions:oa}),ta(this.na),this.od(),this.Ta=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ta,a))}qd(a,c){this.Jb();console.error(`[Preview] Failed to load project main script (${a}): `,
c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}od(){this.Jb()}Jb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Fe(){const a=await ua(this.rb);return{outputPort:a,transferables:[a]}}Ae(){if(this.ca)throw Error("not available in worker mode");return this.Ta}jb(a,c,d,e,f){this.xa.postMessage({type:"event",component:a,handler:c,
dispatchOpts:e||null,data:d,responseId:null},f)}jd(a,c,d,e,f){const g=na++,h=new Promise((m,p)=>{H.set(g,{resolve:m,reject:p})});this.xa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Ge(a);if("result"===c)this.Je(a);else if("runtime-ready"===c)this.Ke();else if("alert-error"===c)this.Jb(),alert(a.message);else if("creating-runtime"===c)this.od();else throw Error(`unknown message '${c}'`);
}Ge(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Ib(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Ib(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Ib(f,!1,""+h)}):this.Ib(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Ib(a,
c,d){let e;d&&d.transferables&&(e=d.transferables);this.xa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Je(a){const c=a.responseId,d=a.isOk;a=a.result;const e=H.get(c);d?e.resolve(a):e.reject(a);H.delete(c)}C(a,c,d){let e=G.get(a);e||(e=new Map,G.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Db(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}ld(){for(const a of this.Ob)if("runtime"===a.mb){this.na=a;return}throw Error("cannot find runtime DOM handler");
}He(a){this.jb("debugger","message",a)}Ke(){for(const a of this.Ob)a.bd()}static hb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||qa)}static Kb(a){qa=!!a}kd(a){this.Ya.push(a);this.Dc()}Ne(a){a=this.Ya.indexOf(a);if(-1===a)throw Error("invalid callback");this.Ya.splice(a,1);this.Ya.length||this.uc()}Dc(){-1===this.Za&&this.Ya.length&&(this.Za=requestAnimationFrame(this.We))}uc(){-1!==this.Za&&(cancelAnimationFrame(this.Za),this.Za=-1)}Ie(){this.Za=
-1;for(const a of this.Ya)a();this.Dc()}Da(a){this.na.Da(a)}Ma(a){this.na.Ma(a)}Cc(){this.na.Cc()}Hb(a){this.na.Hb(a)}oe(){return!!ia["audio/webm; codecs=opus"]}async Pe(a){a=await this.jd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}se(a){this.Nc=!0;this.zd=a}me(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}hd(a){return!this.me(a)}async Oa(a){return"cordova"===this.v&&(a.startsWith("file:")||this.Sb&&this.hd(a))?(a.startsWith(this.ba)&&
(a=a.substr(this.ba.length)),a=await this.Eb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ee(a){const c=a.filename;switch(a.as){case "text":return await this.le(c);case "buffer":return await this.Eb(c);default:throw Error("unsupported type");}}ed(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async le(a){a=await this.ed(a);return await ja(a)}vc(){if(D.length&&!(8<=E)){E++;
var a=D.shift();this.xe(a.filename,a.ef,a.Ye)}}Eb(a){return new Promise((c,d)=>{D.push({filename:a,ef:e=>{E--;this.vc();c(e)},Ye:e=>{E--;this.vc();d(e)}});this.vc()})}async xe(a,c,d){try{const e=await this.ed(a),f=await ka(e);c(f)}catch(e){d(e)}}pd(a){if("entered-fullscreen"===a)b.Kb(!0),I(this.na);else if("exited-fullscreen"===a)b.Kb(!1),I(this.na);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.Zc(a),this.Zc=null):"extension-message"===c?this.jb("runtime","wrapper-extension-message",
a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Le(a){this.Ea({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}Ea(a){this.va()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.v&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Oe(){window.moveTo=(a,c)=>{this.Ea({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=
(a,c)=>{this.Ea({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}De(){return this.va()?new Promise(a=>{this.Zc=a;this.Ea({type:"wrapper-init"})}):Promise.resolve()}async we(){const a=[];for(const [c,d]of Object.entries(this.ra))a.push(this.ve(c,d));await Promise.all(a)}async ve(a,c){if("object"===typeof c)this.ra[a]=new Blob([c.str],{type:c.type}),this.Vb[a]=c.str;else{let d=await this.ze(c);d||(d=this.ye(c));this.ra[a]=d}}async ze(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}ye(a){a=this.Me(a);return this.ue(a.data,a.af)}Me(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{af:a,data:d}}ue(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=
3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const J=self.Ba;function va(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const wa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},xa={dispatchUserScriptEvent:!0},ya={dispatchRuntimeEvent:!0};
function za(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Aa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function L(b){b=URL.createObjectURL(b);try{return await Aa(b)}finally{URL.revokeObjectURL(b)}}
function Ca(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Da(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await L(b);var d=await Ca(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await L(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await L(b)}
function Ea(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Fa=new Set(["input","textarea","datalist","select"]),Ga=new Set(["canvas","body","html"]);function M(b){b.target.tagName&&Ga.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ha(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await L(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Da(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ia=!1;document.addEventListener("pause",()=>Ia=!0);document.addEventListener("resume",()=>Ia=!1);function ta(b){b.yd=!0;b.Qc=b.s.pa();b.sb=b.s.ia()}function I(b){if(!b.$){var a=J.hb();a&&"any"!==b.Wc&&Ja(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.pa(),innerHeight:b.ia()})}}async function Ka(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function La(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ma(b){return await self.C3_GetSvgImageSize(b.blob)}function Na(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Oa(b){self.setTimeout(()=>{b.xd=!0},1E3);"cordova"===b.s.v?(document.addEventListener("pause",()=>Pa(b,!0)),document.addEventListener("resume",()=>Pa(b,!1))):document.addEventListener("visibilitychange",()=>Pa(b,"hidden"===document.visibilityState));b.Zb=!("hidden"!==document.visibilityState&&!Ia);return{isSuspended:b.Zb}}
function Qa(b){b.sd||(b.sd=!0,window.addEventListener("deviceorientation",a=>{b.$||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{b.$||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Ra(b){b.rd||(b.rd=!0,window.addEventListener("devicemotion",a=>{if(!b.$){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Sa(b){await za(b.url)}
function Ta(b,a){b.Ad=a.message;-1===b.Ic&&(b.Ic=setTimeout(()=>{b.Ic=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Ad)},250))}function Ua(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:J.hb(),innerWidth:b.pa(),innerHeight:b.ia()})}function Pa(b,a){b.Zb!==a&&((b.Zb=a)?b.s.uc():b.s.Dc(),k(b,"visibilitychange",{hidden:a}))}
function Va(b,a,c){"Backspace"===c.key&&M(c);if(!b.$){var d=wa.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},K)}}function Wa(b,a,c,d){b.$||va(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function Xa(b){window!==window.top&&window.focus();Ya(b.target)&&document.activeElement&&!Ya(document.activeElement)&&document.activeElement.blur()}
function N(b,a,c){if(!b.$){var d=0;"mouse"===c.pointerType&&(d=b.xb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},K);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Wa(b,d,c,xa),b.xb=c.buttons)}}
function Za(b,a,c){if(!b.$&&!va(c)){var d=b.xb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},K);b.xb=c.buttons;Wa(b,c.type,c,xa)}}
function O(b,a,c){if(!b.$)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
K)}}function $a(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function ab(b,a,c,d){const e=b.pa(),f=b.ia();b.ab=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.hb()}):10>d&&bb(b,e,f,d+1)}
function bb(b,a,c,d){-1!==b.ab&&clearTimeout(b.ab);b.ab=setTimeout(()=>ab(b,a,c,d),48)}
function Ja(b){b=b.Wc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Ya(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.Db(class extends self.eb{constructor(b){super(b,"runtime");this.Gd=!0;this.yd=!1;this.ab=-1;this.Wc="any";this.Zb=this.rd=this.sd=!1;this.ec=document.createElement("div");this.ec.className="c3-screen-reader-text";this.ec.setAttribute("aria-live","polite");document.body.appendChild(this.ec);this.Ha=null;this.$=!1;this.Ad="";this.Ic=-1;this.xd=!1;this.Qc=b.pa();this.sb=b.ia();this.da=this.Bb=0;b.C("canvas","update-size",d=>{var e=this.s;e.Nc||(e=e.J,e.style.width=d.styleWidth+"px",e.style.height=
d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Gd&&(e.style.display="",this.Gd=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Ka(d));b.C("runtime","raster-svg-image",d=>La(d));b.C("runtime",
"get-svg-image-size",d=>Ma(d));b.C("runtime","set-target-orientation",d=>{this.Wc=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Na(d));b.C("runtime","go-to-script",d=>Na(d));b.C("runtime","before-start-ticking",()=>Oa(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ha||(this.Ha=document.createElement("div"),this.Ha.id="inspectOutline",document.body.appendChild(this.Ha));var e=this.Ha;e.style.display=
"";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ha&&(this.Ha.style.display="none")});b.C("runtime","enable-device-orientation",()=>Qa(this));b.C("runtime","enable-device-motion",()=>Ra(this));b.C("runtime","add-stylesheet",d=>Sa(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>this.zc(d));
b.C("runtime","screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.ec.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.$=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.s.J.style.display="";this.s.se(d.duration)});b.C("runtime","export-to-video-progress",d=>Ta(this,d));b.C("runtime","exported-to-video",d=>{window.Xe({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.Xe({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ea(e)||d.preventDefault()});const c=b.J;window.addEventListener("selectstart",M);window.addEventListener("gesturehold",M);c.addEventListener("selectstart",M);c.addEventListener("gesturehold",
M);window.addEventListener("touchstart",M,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",M,{passive:!1}),c.addEventListener("pointerdown",M)):c.addEventListener("touchstart",M);this.xb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ha,{passive:!1});window.addEventListener("wheel",Ha,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.$&&this.yd){var d=this.pa();var e=this.ia();if(this.s.gd()){if(this.xd){if(this.Qc===
d&&e<this.sb){this.Bb=this.sb-e;$a(this,this.sb,this.Bb);d=void 0;break a}0<this.Bb&&(this.Bb=0,$a(this,e,this.Bb))}this.Qc=d;this.sb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.hb()});this.s.qc()&&(-1!==this.ab&&clearTimeout(this.ab),ab(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>I(this));window.addEventListener("webkitfullscreenchange",()=>I(this));window.addEventListener("mozfullscreenchange",()=>
I(this));window.addEventListener("fullscreenerror",d=>Ua(this,d));window.addEventListener("webkitfullscreenerror",d=>Ua(this,d));window.addEventListener("mozfullscreenerror",d=>Ua(this,d));if(b.qc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ea(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});this.Ua=new Set;this.Xb=new WeakSet;this.wa=!1}bd(){window.addEventListener("focus",()=>{k(this,"window-focus",null,ya)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},ya);this.xb=0});window.addEventListener("focusin",a=>{a=a.target;(Fa.has(a.tagName.toLowerCase())||Ea(a))&&
k(this,"keyboard-blur",null,ya)});window.addEventListener("keydown",a=>Va(this,"keydown",a));window.addEventListener("keyup",a=>Va(this,"keyup",a));window.addEventListener("dblclick",a=>Wa(this,"dblclick",a,K));window.addEventListener("wheel",a=>{this.$||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{Xa(a);N(this,"pointerdown",a)}),this.s.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{N(this,"pointermove",a)}):window.addEventListener("pointermove",a=>N(this,"pointermove",a)),window.addEventListener("pointerup",a=>N(this,"pointerup",a)),window.addEventListener("pointercancel",a=>N(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Xa(a);Za(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>Za(this,
"pointermove",a)),window.addEventListener("mouseup",a=>Za(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Xa(a);O(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>O(this,"pointermove",a)),window.addEventListener("touchend",a=>O(this,"pointerup",a)),window.addEventListener("touchcancel",a=>O(this,"pointercancel",a)));const b=()=>this.Cc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",
b,!0);window.addEventListener("gamepadconnected",b,!0);this.s.ne()&&!this.s.gd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{$a(this,this.ia(),navigator.virtualKeyboard.boundingRect.height)}))}pa(){return this.s.pa()}ia(){return this.s.ia()}Cc(){var b=[...this.Ua];this.Ua.clear();if(!this.wa)for(const a of b)(b=a.play())&&b.catch(()=>{this.Xb.has(a)||this.Ua.add(a)})}Da(b){if("function"!==typeof b.play)throw Error("missing play function");
this.Xb.delete(b);let a;try{a=b.play()}catch(c){this.Ua.add(b);return}a&&a.catch(()=>{this.Xb.has(b)||this.Ua.add(b)})}Ma(b){this.Ua.delete(b);this.Xb.add(b)}Hb(b){this.wa=!!b}zc(b){alert(b.message)}});"use strict";
async function ra(b){if(b.Qe)throw Error("already initialised");b.Qe=!0;var a=b.ya.wc(("playable-ad"===b.ya.v?b.ya.$a:"")+"dispatchworker.js");b.Hc=await b.ya.lc(a,b.lb,{name:"DispatchWorker"});a=new MessageChannel;b.Mc=a.port1;b.Hc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Tc=await ua(b)}function sa(b){return[b.Mc,b.Tc]}
async function ua(b){const a=b.Hd.length;var c=b.ya.wc(("playable-ad"===b.ya.v?b.ya.$a:"")+"jobworker.js");c=await b.ya.lc(c,b.lb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Hc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Hd.push(c);return e.port1}
self.qe=class{constructor(b){this.ya=b;this.lb=b.ba;this.lb="preview"===b.v?this.lb+"workers/":this.lb+b.$a;this.Te=Math.min(navigator.hardwareConcurrency||2,16);this.Hc=null;this.Hd=[];this.Tc=this.Mc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Ba({ff:!0,gf:"workermain.js",bb:["scripts/c3runtime.js"],ic:[],$c:"",cf:"scripts/",jc:[],Vd:"html5"}));"use strict";function db(){}
function fb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function gb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.Ba.Db(class extends self.eb{constructor(b){super(b,"browser");this.v="";t(this,[["get-initial-state",a=>{this.v=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
fb(this)],["alert",a=>this.zc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Bc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>gb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||this.s.va()?window.open(c,"_blank"):this.nf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.s.va()||"macos-wkwebview"===this.v)self.Ba.Kb(!0),this.s.Ea({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===
a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(db)}}],["exit-fullscreen",()=>{if(this.s.va()||"macos-wkwebview"===this.v)self.Ba.Kb(!1),this.s.Ea({type:"set-fullscreen",
fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(db)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=
document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}]]);window.addEventListener("online",
()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}zc(b){alert(b.message)}Bc(b){b=b.isFocus;if("nwjs"===this.v){const a="nwjs"===this.v?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";
async function hb(b,a){a=a.type;let c=!0;0===a?c=await ib():1===a&&(c=await jb());k(b,"permission-result",{type:a,result:c})}async function ib(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function jb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.Ba.Db(class extends self.eb{constructor(b){super(b,"touch");n(this,"request-permission",a=>hb(this,a))}});"use strict";const kb=180/Math.PI;
async function lb(b,a){if(a.isiOSCordova||a.isSafari)b.ac=!0;b.Xc=a.timeScaleMode;b.Md=["equalpower","HRTF","soundfield"][a.panningModel];b.vd=["linear","inverse","exponential"][a.distanceModel];b.Nd=a.refDistance;b.Ld=a.maxDistance;b.Pd=a.rolloffFactor;if(b.s.Nc)b.ac=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.s.zd)});else{var c={latencyHint:a.latencyHint};b.Sd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");mb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&mb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Qa=b.g.createGain();b.Qa.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ea);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function nb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,m=a.vol,p=a.pos,q=a.panning,A=a.stereoPan;let x=a.off;0<x&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+b.g.currentTime);b.Id=g.slice(0);ob(b,g);try{b.R=await pb(b,c,d,e,g,f);if(q){Q(b.R,!0);var r=b.R,B=q.innerAngle,la=q.outerAngle,ma=q.outerGain;if(r.qb){qb(r,q.x,q.y,q.z,q.angle);var C=self.cb.te;r.sa[0]!==C(B)&&
(r.sa[0]=C(B),r.F.coneInnerAngle=C(B));r.sa[1]!==C(la)&&(r.sa[1]=C(la),r.F.coneOuterAngle=C(la));r.sa[2]!==ma&&(r.sa[2]=ma,r.F.coneOuterGain=ma)}q.hasOwnProperty("uid")&&(b.R.qa=q.uid)}else"number"===typeof A&&0!==A?(R(b.R,!0),rb(b.R,A)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,m,p,x)}catch(Db){console.error("[Construct] Audio: error starting playback: ",Db);return}finally{c=g.join(" ");d=b.zb.get(c);if(!d)throw Error("expected pending tag");d.ad--;0===d.ad&&(d.resolve(),b.zb.delete(c))}u(b)}
async function sb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await tb(b,c);for(const h of S(b,c))if(!h.Sa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ka=d;h.Ra=g;h.Rd=a}T(b)}async function ub(b,a){const c=a.tags;a=a.rate;await tb(b,c);for(const d of S(b,c))d.ma!==a&&(d.ma=a,d.Fa())}async function vb(b,a){const c=a.tags;a=a.pos;await tb(b,c);for(const d of S(b,c))d.rc(a)}
async function wb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await pb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function xb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ka.indexOf(a),-1!==a&&b.ka.splice(a,1)}
async function yb(b,a){const c=a.type;var d=a.tags;const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct] Audio: error loading convolution: ",m);return}for(const m of d){if("filter"===c)d=new self.ae(b,...e);else if("delay"===c)d=new self.Zd(b,...e);else if("convolution"===c){var g=d=new self.Yd(b,f.ja,...e),h=a.bufferType;g.td=a.bufferOriginalUrl;g.ud=h}else if("flanger"===c)d=new self.be(b,...e);else if("phaser"===
c)d=new self.de(b,...e);else if("gain"===c)d=new self.ce(b,...e);else if("stereopan"===c)d=new self.fe(b,...e);else if("tremolo"===c)d=new self.ge(b,...e);else if("ringmod"===c)d=new self.ee(b,...e);else if("distortion"===c)d=new self.$d(b,...e);else if("compressor"===c)d=new self.Xd(b,...e);else if("analyser"===c)d=new self.Wd(b,...e);else throw Error("invalid effect type");g=b;h=m;h=h.toLowerCase();let p=g.la.get(h);p||(p=[],g.la.set(h,p));d.Fd=p.length;d.Vc=h;p.push(d);zb(g,h)}Ab(b)}
async function Bb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Aa()&&1===c||!e.Aa()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.la.values())for(const g of f)g.j();b.la.clear();b.fc=a.timeScale;b.Jc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ea[e]=d[e];b.g.listener.setOrientation(...b.ea)}b.wa=a.isSilent;b.s.Hb(b.wa);b.Wb=a.masterVolume;b.Qa.gain.value=
b.Wb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>yb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Cb(b,f,c)));T(b)}
async function Eb(b,a){try{const c=b.g.suspend(a.time);b.Ed?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.s.jb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Fb(d)),b.Ed=!0);await c}catch(c){Fb(c)}}
function mb(b){b.Qb||(b.Lc=!1,window.addEventListener("pointerup",b.za,!0),window.addEventListener("touchend",b.za,!0),window.addEventListener("click",b.za,!0),window.addEventListener("keydown",b.za,!0),b.Qb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ka)if(g.gb()===c)return await Gb(g),g;if(f)return null;if(e&&(b.ac||b.Dd)){f=0;for(let h=0,m=b.ka.length;h<m;++h)g=b.ka[h],b.ka[f]=g,g.Aa()?g.j():++f;b.ka.length=f}f="audio/webm; codecs=opus"===d&&!b.Sd;e&&f&&(b.Dd=!0);c=!e||b.ac||f?new self.je(b,a,c,d,e,f):new self.he(b,a,c,d,e);b.ka.push(c);await Gb(c);b.Kd.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ha()}),b.Kd.add(a));return c}
function Hb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Ib(b,a){return(a=b.la.get(a.toLowerCase()))?a[0].N():b.ga()}function zb(b,a){a=a.toLowerCase();let c=b.ga();var d=b.la.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ga()):e.U(d[f+1].N())}}for(const f of Jb(b,a))d=c,e=f.fa||f.F||f.G,e.disconnect(),e.connect(d);b.Ia&&b.Rc===a&&(b.Ia.disconnect(),b.Ia.connect(c))}
function*Jb(b,a){if(a)for(const c of b.H)Hb(0<c.oa.length?c.oa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Kb(b,a,c){return c?b.s.Pe(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Lb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.oa;var c=a;for(const e of c){c=!1;for(const f of b)if(Hb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function pb(b,a,c,d,e,f){for(const g of b.H)if(g.gb()===c&&(g.kc()||f))return g.oa=e,g;a=await P(b,a,c,d,f);e="html5"===a.Ec?new self.ie(a.u,a,e):new self.ke(a.u,a,e);b.H.push(e);return e}
function ob(b,a){a=a.join(" ");let c=b.zb.get(a);if(!c){let d=null;c={ad:0,promise:new Promise(e=>d=e),resolve:d};b.zb.set(a,c)}c.ad++}function tb(b,a){return(b=b.zb.get((0===a.length?b.Id:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Pa.size)u(b);else for(const a of b.H)if(!a.I&&!a.O()){u(b);break}}function Mb(b,a,c,d){k(b,"trigger",{type:a,tags:c,aiid:d})}function Ab(b){b.Oc||(b.Oc=!0,Promise.resolve().then(()=>Nb(b)))}
function Nb(b){const a={};for(const [c,d]of b.la)a[c]=d.map(e=>e.fb());k(b,"fxstate",{fxstate:a});b.Oc=!1}
async function Cb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,m=a.isLooping,p=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await pb(b,d,e,f,h,g)}catch(A){console.error("[Construct] Audio: error loading audio state: ",A);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Wa[0]=f[0],b.Wa[1]=f[1],b.Wa[2]=f[2],f=d.orient,b.Va[0]=f[0],b.Va[1]=f[1],b.Va[2]=f[2],e.setPosition(...b.Wa),e.setOrientation(...b.Va),b.sa[0]=d.cia,b.sa[1]=d.coa,b.sa[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.qa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),rb(b,d));c.Play(m,p,q,0);a.isPlaying||c.ib();c.yc(a)}}}function Fb(b){console.error("[Audio] Offline rendering error: ",b)}
self.cb=class extends self.eb{constructor(b){super(b,"audio");this.Qa=this.g=null;this.Qb=this.Lc=!1;this.za=()=>{if(!this.Lc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Qb&&(this.Lc=!0,window.removeEventListener("pointerup",this.za,!0),window.removeEventListener("touchend",this.za,!0),window.removeEventListener("click",this.za,!0),window.removeEventListener("keydown",
this.za,!0),this.Qb=!1)}};this.ka=[];this.H=[];this.R=null;this.Id=[];this.Kd=new Set;this.Jd=-1;this.zb=new Map;this.Wb=1;this.wa=!1;this.Xc=0;this.fc=1;this.Jc=0;this.Md="HRTF";this.vd="inverse";this.Nd=600;this.Ld=1E4;this.Pd=1;this.aa=[0,0,0];this.ea=[0,0,-1,0,1,0];this.Dd=this.ac=!1;this.Sd=this.s.oe();this.la=new Map;this.Pa=new Set;this.Ed=this.Oc=!1;this.Rc="";this.Ia=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ia&&this.Ia.disconnect();this.Rc=c.toLowerCase();this.Ia=this.g.createMediaStreamSource(a);
this.Ia.connect(Ib(this,this.Rc))};this.Nb=null;self.C3Audio_GetOutputStream=()=>{this.Nb||(this.Nb=this.g.createMediaStreamDestination(),this.Qa.connect(this.Nb));return this.Nb.stream};self.C3Audio_DOMInterface=this;t(this,[["create-audio-context",a=>lb(this,a)],["play",a=>nb(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Ca()}],["stop-all",()=>{for(const a of this.H)a.Ca()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.ib():d.Gb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>sb(this,a)],["set-master-volume",a=>{this.Wb=a.vol;this.Qa.gain.value=this.Wb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Ob(d,a)}],["set-silent",a=>{this.wa=a.isSilent;this.s.Hb(this.wa);for(const c of this.H)c.Lb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.sc(a)}],["set-playback-rate",a=>ub(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),rb(d,a)}],["seek",a=>vb(this,a)],["preload",a=>wb(this,a)],["unload",a=>xb(this,a)],["unload-all",()=>{for(const a of this.ka)a.j();this.ka.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.tc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>yb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.la.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);Ab(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.la.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.la.delete(a);zb(this,a)}}],["tick",a=>{this.fc=a.timeScale;this.Jc=a.gameTime;this.Jd=a.tickCount;if(0!==this.Xc)for(var c of this.H)c.Fa();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ea[0]!==
c[0]||this.ea[1]!==c[1]||this.ea[2]!==c[2]||this.ea[3]!==c[3]||this.ea[4]!==c[4]||this.ea[5]!==c[5])){for(let d=0;6>d;++d)this.ea[d]=c[d];this.g.listener.setOrientation(...this.ea)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.qa===a&&qb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Bb(this,a)],["offline-render-audio",a=>Eb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ga(){return this.Qa}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ga()}Fb(){return this.wa}Da(b){this.s.Da(b)}Ma(b){this.s.Ma(b)}Na(){for(var b of this.Pa)b.Na();
b=this.g.currentTime;for(var a of this.H)a.Na(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.fb());k(this,"state",{tickCount:this.Jd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Pa].map(c=>({tag:c.Vc,index:c.Fd,peak:c.Xa,rms:c.Od,binCount:c.l.frequencyBinCount,freqBins:c.Bd}))});0===a.length&&0===this.Pa.size&&this.Rb&&(this.s.Ne(this.Td),this.Rb=!1)}static te(b){return b*kb}static fd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static re(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.Ba.Db(self.cb);"use strict";function Gb(b){b.Ub||(b.Ub=b.xc());return b.Ub}self.cd=class{constructor(b,a,c,d,e){this.u=b;this.Ve=a;this.Ja=c;this.T=d;this.Re=e;this.Ec="";this.Ub=null}j(){this.Ub=this.u=null}xc(){}V(){return this.u.V()}nc(){return this.Ve}gb(){return this.Ja}mc(){return this.T}Aa(){return this.Re}ha(){}};"use strict";
self.he=class extends self.cd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Ec="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.tb=this.ub=null;this.M.addEventListener("canplaythrough",()=>!0);this.yb=this.V().createGain();this.wb=null;this.M.addEventListener("canplay",()=>{this.ub&&(this.ub(),this.tb=this.ub=null);!this.wb&&this.M&&(this.wb=this.V().createMediaElementSource(this.M),this.wb.connect(this.yb))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ja}' error: `,f);this.tb&&(this.tb(f),this.tb=this.ub=null)})}j(){Lb(this.u,this);this.yb.disconnect();this.yb=null;this.wb.disconnect();this.wb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}xc(){return new Promise((b,a)=>{this.ub=b;this.tb=a;this.M.src=this.Ja})}W(){return this.M}ha(){return this.M.duration}};"use strict";
async function Pb(b){if(b.Ga)return b.Ga;var a=b.u.s;if("cordova"===a.v&&a.hd(b.Ja)&&a.Sb)b.Ga=await a.Eb(b.Ja);else{a=await fetch(b.Ja);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ga=await a.arrayBuffer()}}async function Qb(b){if(b.ja)return b.ja;b.ja=await Kb(b.u,b.Ga,b.Ue);b.Ga=null}
self.je=class extends self.cd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Ec="webaudio";this.ja=this.Ga=null;this.Ue=!!f}j(){Lb(this.u,this);this.ja=this.Ga=null;super.j()}async xc(){try{await Pb(this),await Qb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ja}': `,b)}}ha(){return this.ja?this.ja.duration:0}};"use strict";let Rb=0;
function Q(b,a){a=!!a;b.qb!==a&&(b.qb=a,b.qb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.Md,b.F.distanceModel=b.u.vd,b.F.refDistance=b.u.Nd,b.F.maxDistance=b.u.Ld,b.F.rolloffFactor=b.u.Pd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ga())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ga())))}
function R(b,a){a=!!a;b.Tb!==a&&(b.Tb=a,b.Tb?(Q(b,!1),b.fa=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.fa),b.fa.connect(b.ga())):(b.fa.disconnect(),b.fa=null,b.G.disconnect(),b.G.connect(b.ga())))}function rb(b,a){b.Tb&&b.Uc!==a&&(b.fa.pan.value=a,b.Uc=a)}function U(b,a){b.Ka=a;b.G.gain.cancelScheduledValues(0);b.Ra=-1;b.G.gain.value=b.oc()}function Ob(b,a){a=!!a;b.Sa!==a&&(b.Sa=a,b.Lb())}
function qb(b,a,c,d,e){if(b.qb){var f=b.Wa,g=b.Va,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Pc?b.u.Jc:performance.now()/1E3}
self.dd=class{constructor(b,a,c){this.u=b;this.P=a;this.oa=c;this.Mb=Rb++;this.G=this.V().createGain();this.G.connect(this.ga());this.F=null;this.qb=!1;this.Wa=[0,0,0];this.Va=[0,0,0];this.sa=[0,0,0];this.fa=null;this.Tb=!1;this.Uc=0;this.I=!0;this.Y=this.ta=this.K=!1;this.Ka=1;this.Sa=!1;this.ma=1;b=this.u.Xc;this.Pc=1===b&&!this.Aa()||2===b;this.Ra=this.qa=-1;this.Rd=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.fa&&(this.fa.disconnect(),this.fa=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}ga(){return Ib(this.u,0<this.oa.length?this.oa[0]:"")}nc(){return this.P.nc()}gb(){return this.P.gb()}mc(){return this.P.mc()}Aa(){return this.P.Aa()}O(){}kc(){}IsPlaying(){return!this.I&&!this.K&&!this.O()}La(){}ha(){return this.P.ha()}Play(){}Ca(){}ib(){}Gb(){}Na(b){-1!==this.Ra&&b>=this.Ra&&(this.Ra=-1,this.Rd&&this.Ca(),Mb(this.u,"fade-ended",this.oa,this.Mb))}oc(){const b=this.Ka;return isFinite(b)?b:0}Fb(){return this.u.Fb()}Lb(){}sc(){}Fa(){}rc(){}tc(){}pc(){}fb(){var b=
this.Mb,a=this.oa,c=this.ha(),d=-1===this.Ra?this.Ka:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Wa,orient:this.Va,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.qa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.La(),playbackRate:this.ma,uid:this.qa,bufferOriginalUrl:this.nc(),bufferUrl:"",bufferType:this.mc(),isMusic:this.Aa(),isLooping:this.Y,isMuted:this.Sa,resumePosition:this.pc(),pan:f,stereoPan:this.fa?
this.Uc:null}}yc(b){var a=b.playbackRate;this.ma!==a&&(this.ma=a,this.Fa());Ob(this,b.isMuted)}};"use strict";
self.ie=class extends self.dd{constructor(b,a,c){super(b,a,c);this.P.yb.connect(this.G);this.P.onended=()=>this.Ac()}j(){this.Ca();this.P.yb.disconnect();super.j()}W(){return this.P.W()}Ac(){this.I=!0;this.qa=-1;Mb(this.u,"ended",this.oa,this.Mb)}O(){return this.W().ended}kc(){return this.I?!0:this.O()}La(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.ha()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.gb()}' to position '${c}': `,e)}this.u.Da(d);this.K=this.I=!1;this.Y=b;this.ma=1}Ca(){const b=this.W();b.paused||b.pause();this.u.Ma(b);this.I=!0;this.K=!1;this.qa=-1}ib(){if(!(this.K||this.I||this.O())){var b=this.W();b.paused||b.pause();this.u.Ma(b);this.K=!0}}Gb(){!this.K||this.I||this.O()||(this.u.Da(this.W()),this.K=!1)}Lb(){this.W().muted=this.Sa||this.Fb()}sc(b){b=!!b;this.Y!==b&&(this.Y=
b,this.W().loop=b)}Fa(){let b=this.ma;this.Pc&&(b*=this.u.fc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}rc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}pc(){return this.La()}tc(b){b?this.IsPlaying()?(this.W().pause(),this.ta=!0):this.ta=!1:this.ta&&(this.u.Da(this.W()),this.ta=!1)}};"use strict";
function W(b){b.o&&(b.o.onended=null,b.o.disconnect(),b.o.buffer=null);b.o=null;b.kb=null}
self.ke=class extends self.dd{constructor(b,a,c){super(b,a,c);this.o=null;this.Yb=d=>this.Ac(d);this.Kc=!0;this.kb=null;this.S=this.$b=this.bc=0;this.Sc=1}j(){this.Ca();W(this);this.Yb=null;super.j()}Ac(b){this.K||this.ta||b.target!==this.kb||(this.I=this.Kc=!0,this.qa=-1,W(this),Mb(this.u,"ended",this.oa,this.Mb))}O(){return!this.I&&this.o&&this.o.loop||this.K?!1:this.Kc}kc(){return!this.o||this.I?!0:this.O()}La(){let b;b=this.K?this.S:this.$b+(V(this)-this.bc)*this.ma;this.Y||(b=Math.min(b,this.ha()));
return b}Play(b,a,c,d){this.Sc=1;U(this,a);W(this);this.o=this.V().createBufferSource();this.o.buffer=this.P.ja;this.o.connect(this.G);this.kb=this.o;this.o.onended=this.Yb;this.o.loop=b;this.o.start(d,c);this.K=this.I=this.Kc=!1;this.Y=b;this.ma=1;this.bc=V(this);this.$b=c}Ca(){if(this.o)try{this.o.stop(0)}catch(b){}this.I=!0;this.K=!1;this.qa=-1}ib(){this.K||this.I||this.O()||(this.S=this.La(),this.Y&&(this.S%=this.ha()),this.K=!0,this.o.stop(0))}Gb(){!this.K||this.I||this.O()||(W(this),this.o=
this.V().createBufferSource(),this.o.buffer=this.P.ja,this.o.connect(this.G),this.kb=this.o,this.o.onended=this.Yb,this.o.loop=this.Y,U(this,this.Ka),this.Fa(),this.o.start(0,this.S),this.bc=V(this),this.$b=this.S,this.K=!1)}oc(){return super.oc()*this.Sc}Lb(){this.Sc=this.Sa||this.Fb()?0:1;U(this,this.Ka)}sc(b){b=!!b;this.Y!==b&&(this.Y=b,this.o&&(this.o.loop=b))}Fa(){let b=this.ma;this.Pc&&(b*=this.u.fc);this.o&&(this.o.playbackRate.value=b)}rc(b){this.I||this.O()||(this.K?this.S=b:(this.ib(),this.S=
b,this.Gb()))}pc(){return this.S}tc(b){b?this.IsPlaying()?(this.ta=!0,this.S=this.La(),this.Y&&(this.S%=this.ha()),this.o.stop(0)):this.ta=!1:this.ta&&(W(this),this.o=this.V().createBufferSource(),this.o.buffer=this.P.ja,this.o.connect(this.G),this.kb=this.o,this.o.onended=this.Yb,this.o.loop=this.Y,U(this,this.Ka),this.Fa(),this.o.start(0,this.S),this.bc=V(this),this.$b=this.S,this.ta=!1)}yc(b){super.yc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.u=b;this.g=b.V();this.Fd=-1;this.T=this.Vc="";this.m=null}j(){this.g=null}N(){}U(){}fb(){return{type:this.T,tag:this.Vc,params:this.m}}}
self.ae=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.A=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}j(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.Zd=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.vb=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.ob=X(this);this.ob.gain.value=c;this.A.connect(this.vb);this.A.connect(this.h);this.vb.connect(this.i);this.vb.connect(this.X);this.X.connect(this.ob);this.ob.connect(this.vb)}j(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.vb.disconnect();
this.X.disconnect();this.ob.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.cb.fd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.ob.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.Yd=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.ud=this.td="";this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.nb=this.g.createConvolver();this.nb.normalize=c;this.nb.buffer=a;this.A.connect(this.nb);this.A.connect(this.h);this.nb.connect(this.i)}j(){this.A.disconnect();this.nb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}fb(){const b=super.fb();b.bufferOriginalUrl=this.td;b.bufferUrl="";b.bufferType=this.ud;return b}};
self.be=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.A=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.pb=X(this);this.pb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.L=X(this);this.L.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.pb);this.pb.connect(this.X);this.B.connect(this.L);
this.L.connect(this.X.delayTime);this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.X.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.pb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.B.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.pb.gain,a/100,c,d)}}};
self.de=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.A=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.L=X(this);this.L.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.B.connect(this.L);this.L.connect(this.D.frequency);
this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.D.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.B.frequency,a,c,d)}}};self.ce=class extends Z{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.cb.fd;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.fe=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.ge=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.L=X(this);this.L.gain.value=c/2;this.B.connect(this.L);this.L.connect(this.l.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.L.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.ee=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.A=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Ab=X(this);this.Ab.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.Ab.gain);this.B.start(0);this.A.connect(this.Ab);this.A.connect(this.h);this.Ab.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.Ab.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.$d=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.A=X(this);this.dc=X(this);this.cc=X(this);b=d;.01>b&&(b=.01);this.dc.gain.value=b;this.cc.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.hc=this.g.createWaveShaper();this.Gc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Gc[32768+e]=f,this.Gc[32768-
e-1]=-f;this.hc.curve=this.Gc;this.A.connect(this.dc);this.A.connect(this.h);this.dc.connect(this.hc);this.hc.connect(this.cc);this.cc.connect(this.i)}j(){this.A.disconnect();this.dc.disconnect();this.hc.disconnect();this.cc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.Xd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.Wd=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Bd=new Float32Array(this.l.frequencyBinCount);this.Qd=new Uint8Array(a);this.Od=this.Xa=0;b=this.u;b.Pa.add(this);T(b)}j(){this.u.Pa.delete(this);this.l.disconnect();super.j()}Na(){this.l.getFloatFrequencyData(this.Bd);this.l.getByteTimeDomainData(this.Qd);const b=this.l.fftSize;let a=this.Xa=0;for(var c=0;c<b;++c){let d=(this.Qd[c]-
128)/128;0>d&&(d=-d);this.Xa<d&&(this.Xa=d);a+=d*d}c=self.cb.re;this.Xa=c(this.Xa);this.Od=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
